version: '2'
services:
  gitlab:
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - /srv/gitlab/config:/etc/gitlab
     - /srv/gitlab/log:/var/log/gitlab
     - /srv/gitlab/data:/var/opt/gitlab
    image: gitlab/gitlab-ce:latest
  jenkins:
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - /srv/jenkins/:/var/jenkins_home
    user: root
    image: jenkins:latest

